#New customer page elements
click_newcustomerlink ="//a[@href='addcustomerpage.php'  ]"
txt_cust_name ="//input[@type='text' and @name='name']"
txt_genderMale ="//input[@value='m' and @name='rad1']"
txt_genderFemale ="//input[@value='f' and @name='rad1']"
txt_dob="//input[@type='date' and @name='dob']"
txt_address="//textarea[@name='addr']"
txt_city ="//input[@name='city' and @type='text' ]"
txt_state ="//input[@name='state' and @type='text' ]"
txt_pin="//input[@name='pinno' and @type='text' ]"
txt_mobileno="//input[@name='telephoneno' and @type='text' ]"
txt_emailid ="//input[@name='emailid' and @type='text' ]"
txt_newcustpassword ="//input[@name='password' and @type='password' ]"
click_newcust_submitbutton="//input[@name='sub'  ]"
click_newcust_resetbutton ="//input[@name='res'  ]"